### ISSUE TITLE
Emacs hangs with special continuation line

### ISSUE THREAD

**Issue by MichaelManert** [mattfidler/nsis-mode#14]
Emacs hangs, if a continuation line starts with an equal sign.
How to reproduce:

load a file with nsis-mode
;====== snippet begin ====
MessageBox MB_OK "Installation failed!$\r$\n\
#= abort installation"

MessageBox MB_OK "Installation failed!$\r$\n\
 = abort installation"
;====== snippet end ====

delete the hash => emacs hangs immediately and needs to be killed

**Comment by mattfidler** [comment]
I'm assuming the pull request fixed this.

Thanks for your help.
