### ISSUE TITLE
Compile commands fail on 64 bit emacs

### ISSUE THREAD

**Issue by billthefarmer** [mattfidler/nsis-mode#6]
The compile commands use `(getenv "ProgramFiles")` to find the NSIS executables. This doesn't work on a 64 bit machine with 64 bit emacs because NSIS is currently 32 bit. It can be fixed as a kludge by substituting `(getenv "ProgramFiles(x86)")`, but that might not work on a 32 bit machine. I don't know enough about emacs Lisp to come up with a generic solution.

**Comment by mattfidler** [comment]
I'm not sure if this works for you, but it should work.

I will close this for now, unless you state that it doens't work.

**Comment by billthefarmer** [comment]
Yes, that works, thank you. I get compile warnings and an error when I install the new version, but that was the same as before, I think.
